[toolchain]
channel = "nightly-2024-09-05" # Make sure to update `template/*/rust-toolchain.toml` as well.
components = ["rustfmt", "clippy"]
targets = ["wasm32-unknown-unknown", "x86_64-unknown-linux-musl"]
