apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gossip-kv-seed-nodes
  labels:
    app: gossip-kv-seed-nodes
spec:
  replicas: 3
  serviceName: gossip-kv-seed-nodes
  selector:
    matchLabels:
      app: gossip-kv-seed-nodes
  template:
    metadata:
      labels:
        app: gossip-kv-seed-nodes
    spec:
      terminationGracePeriodSeconds: 5 # Really aggressive, but makes teardown faster. Not recommended beyond benchmarking.
      containers:
        - name: gossip-kv-server
          image: docker.io/hydroflow/gossip-kv-server:latest
          imagePullPolicy: IfNotPresent
#          Uncomment the following for debugging
#          command: [ "/bin/sh" ]
#          args: [ "-c", "while true; do sleep 3600; done" ]
          env:
            - name: RUST_LOG
              value: "trace"
            - name: RUST_BACKTRACE
              value: "full"
          ports:
            - containerPort: 3001
              protocol: UDP
          volumeMounts:
            - name: gossip-kv-dynamic-config
              mountPath: /config/dynamic
      volumes:
        - name: gossip-kv-dynamic-config
          configMap:
            name: gossip-kv-dynamic-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gossip-kv-cli
  labels:
    app: gossip-kv-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gossip-kv-cli
  template:
    metadata:
      labels:
        app: gossip-kv-cli
    spec:
      terminationGracePeriodSeconds: 5 # Really aggressive, but makes teardown faster. Not recommended beyond benchmarking.
      containers:
        - name: gossip-kv-cli
          image: docker.io/hydroflow/gossip-kv-cli:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh"]
          args: ["-c", "while true; do sleep 3600; done"]
          tty: true
          env:
            - name: RUST_LOG
              value: "info"
---
apiVersion: v1
kind: Service
metadata:
  name: gossip-kv-seed-nodes
  labels:
    app: gossip-kv-seed-nodes
spec:
  ports:
    - port: 3001
      targetPort: 3001
      protocol: UDP
  clusterIP: None
  selector:
    app: gossip-kv-seed-nodes
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gossip-kv-dynamic-config
data:
  dynamic.toml: |