[package]
name = "hydro_cli"
publish = true
version = "0.10.0"
edition = "2021"
license = "Apache-2.0"
documentation = "https://docs.rs/hydro_cli/"
description = "Hydro Deploy Command Line Interface"

[lints]
workspace = true

[lib]
name = "hydro_cli"
# "cdylib" is necessary to produce a shared library for Python to import from.
crate-type = ["cdylib"]

[dependencies]
hydro_deploy = { path = "../core", version = "^0.10.0" }
tokio = { version = "1.29.0", features = [ "full" ] }
anyhow = { version = "1.0.82", features = [ "backtrace" ] }
clap = { version = "4.5.4", features = ["derive"] }
pyo3 = { version = "0.20.0", features = ["abi3-py37"] }
pyo3-asyncio = { version = "0.20.0", features = ["attributes", "tokio-runtime"] }
pythonize = "0.20.0"
futures = "0.3.0"
bytes = "1.1.0"
hydroflow_deploy_integration = { path = "../hydroflow_deploy_integration", version = "^0.10.0" }

# request vendored openssl
async-ssh2-lite = { version = "0.5.0", features = [ "vendored-openssl" ] }
