[package]
name = "lattices-fuzz"
path = "src/lib.rs"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
once_cell = "1.8.0"


[dependencies.lattices]
path = ".."

[[bin]]
name = "associativity_fuzz"
path = "fuzz_targets/associativity_fuzz.rs"
test = false
doc = false
bench = false

[[bin]]
name = "commutativity_fuzz"
path = "fuzz_targets/commutativity_fuzz.rs"
test = false
doc = false
bench = false

[[bin]]
name = "distributivity_fuzz"
path = "fuzz_targets/distributivity_fuzz.rs"
test = false
doc = false
bench = false

[[bin]]
name = "linearity_fuzz"
path = "fuzz_targets/linearity_fuzz.rs"
test = false
doc = false
bench = false


[[bin]]
name = "monotonicity_fuzz"
path = "fuzz_targets/monotonicity_fuzz.rs"
test = false
doc = false
bench = false